---
name: manual-deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: ${{ vars.DOKKU_GIT_REMOTE_URL}}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}